### ISSUE TITLE
Updating tsconfig target to ES2023 breaks building with TypeScript <5.5.0

### ISSUE THREAD

**Issue by TheVaan** [fastify/tsconfig#6]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched existing issues to ensure the regression has not already been reported

### Last working version

2.0.0

### Stopped working in version

3.0.0

### Node.js version

22.12.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.7.2

### 💥 Regression Report

We were using fastify v5 with v2 of fastify/tsconfig with no issues. After upgrading fastify/tsconfig to v3, the build process is broken:
```
node_modules/fastify-tsconfig/tsconfig.json:4:15 - error TS6046: Argument for '--target' option must be: 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext'.

4     "target": "ES2023",
```

The reason is the usage of TypeScript 5.4.5 (I know, that's quite old - we could upgrade this, but we have several projects on 5.4.5 that can't be easily upgraded due to dependencies so we want to stay at 5.4.5 for now) that doesn't support `ES2023` as build target in tsconfig compile options (see https://github.com/microsoft/TypeScript/issues/57683 - got fixed with 5.5.0).

Tbh I don't know why setting target to ES2023 should be necessary for fastify v5 (as claimed [here](https://github.com/fastify/tsconfig/issues/3)). I think ES2022 would be fine (worked for us) or even ESNext (would pick the highest available version).

I tried overwriting target version but somehow `tsc` seems to check the target version of the linked base file that should be extended.

My tsconfig:
```
{
  "extends": "fastify-tsconfig",
  "compilerOptions": {
    "target": "ESNext",
    "outDir": "dist",
    "sourceMap": true,
  },
}
```

My `npm run build` command: `tsc -p tsconfig.json`

I downgraded `fastify/tsconfig` and everything is working fine. If you want to stay hat ES2023, the change should be marked as breaking change and peer dependency to TypeScript >=5.5.0 should be mentioned.

### Steps to Reproduce

Setup environment with typescript below version 5.5.0.

**Comment by mcollina** [comment]
I don't really understand this regression report. There was a breaking change in v3.0.0 of this module, which you upgraded to, and then reverted that change because you can't or won't update your typescript compiler. If it wasn't breaking, it would have been a minor release.

**Comment by TheVaan** [comment]
Well, major release **can** contain breaking but when the change log only contains `chore` changes I think no one assumes that these **chores** are breaking changes. 

It's not about fixing a bug in first place. It's more about communication (e.g. marking chore as breaking).

But yea, maybe I just didn't know that a major release MUST have breaking changes, even if they are not marked as breaking in conventional commit.


I'm closing this.
